# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
